SectionVerb {
	EnableSequence [
		cset "name='Left SPK Mixer Left DAC1' on"
		cset "name='Right SPK Mixer Right DAC1' on"
		cset "name='Speaker' 100%"
		cset "name='Left HP Mixer Left DAC1' on"
		cset "name='Right HP Mixer Right DAC1' on"
		cset "name='Headphone' 100%"
	]
	DisableSequence [
		cset "name='Speaker' 0%"
		cset "name='Headphone' 0%"
	]
}

SectionDevice."Speaker" {
	Comment "Speaker"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId}"
	}
	EnableSequence [
		cset "name='Left SPK Mixer Left DAC1' on"
		cset "name='Right SPK Mixer Right DAC1' on"
		cset "name='Speaker' 100%"
	]
	DisableSequence [
		cset "name='Speaker' 0%"
		cset "name='Left SPK Mixer Left DAC1' off"
		cset "name='Right SPK Mixer Right DAC1' off"
	]
}

SectionDevice."Headphones" {
	Comment "Headphones"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId}"
	}
	EnableSequence [
		cset "name='Left HP Mixer Left DAC1' on"
		cset "name='Right HP Mixer Right DAC1' on"
		cset "name='Headphone' 100%"
	]
	DisableSequence [
		cset "name='Headphone' 0%"
		cset "name='Left HP Mixer Left DAC1' off"
		cset "name='Right HP Mixer Right DAC1' off"
	]
}
